MENU_WIDTH = 852
MENU_HEIGHT = 480

OPT_WIDTH = 600
OPT_HEIGHT = 530

GAME_WIDTH = 900
GAME_HEIGHT = 900

ROWS = 19
COLS = 19
SQSIZE = GAME_WIDTH // COLS

BACKGROUND = "white"
TRANSPARENT = "#fefefe"
BUTTON_COL = "black"
BUTTON_COL_CLICKED = "#ff9e17"
BUTTON_COL_SELECTED = "#1677ff"
FONT = ""